// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Document = 1,
  TikzPicture = 2,
  BeginTikz = 3,
  Scope = 4,
  BeginScope = 5,
  EndScope = 6,
  Statement = 7,
  Command = 8,
  Group = 9,
  BracketGroup = 10,
  Parenthesized = 11,
  MathGroup = 12,
  Comment = 13,
  Atom = 14,
  EndTikz = 15
