// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "&fQVQPOOO!`QPO'#C`O!gQPO'#CeO!nQPO'#CfO!uQPO'#CgO#bQPO'#ChO$QQPO'#CcO$XQPO'#C^OOQO'#Cs'#CsOOQO'#Cl'#ClQVQPOOOOQO,58z,58zO$`QPO,58zOOQO'#Ct'#CtOOQO'#Cm'#CmOOQO,59P,59PO$gQPO,59POOQO,59Q,59QO$nQPO,59QOOQO,59R,59RO$uQPO,59ROOQO'#C}'#C}OOQO'#Co'#CoO$|QPO,59SOOQO,59S,59SOOQO'#Cu'#CuOOQO'#Cn'#CnO%TQPO,58}OOQO,58},58}O%[QPO,58xOOQO,58x,58xOOQO-E6j-E6jOOQO1G.f1G.fOOQO-E6k-E6kOOQO1G.k1G.kOOQO1G.l1G.lOOQO1G.m1G.mOOQO-E6m-E6mOOQO1G.n1G.nOOQO-E6l-E6lOOQO1G.i1G.iOOQO1G.d1G.d",
  stateData: "%l~OfOS~ORVOTPOWUO]WO^WOjQOlROnSOpTO~OTPOWUO]]O^]OjQOlROnSOpTO~OUZO~PtOk_O~PVOmaO~PVOocO~PVOWeO]eO^eOjQOlROnSO~OphO~P!|OWiO]iO^iOjQOlROnSOpTO~OrlO~P#iO_nO~PtOUpO~PtOkrO~PVOmsO~PVOotO~PVOpvO~P!|OrxO~P#iO_yO~PtOR_TUW]^U~",
  goto: "$orPPsP}PP}P!_!_!_!wPPP#]#o#y$PPPP$V$a$gPPPPPPP$kaWOQRSY`bd`WOQRSY`bdX]PV[m`WOQRSY`bdW]PV[mSeTgTiUk`WOQRSY`bdW]PV[mTiUkQYOQ`QQbRQdSXoY`bdQ[PQmVTq[mQkURwkQgTRugaXOQRSY`bdX^PV[mTjUkTfTg",
  nodeNames: "⚠ Document TikzPicture BeginTikz Scope BeginScope EndScope Statement Command Group BracketGroup Parenthesized MathGroup Comment Atom EndTikz",
  maxTerm: 34,
  skippedNodes: [0],
  repeatNodeCount: 4,
  tokenData: ".T~RjOX!sXY#tYZ#tZ]!s]^#t^p!spq#tqt!stu$Vuv$[vx!sxy$vyz${z!]!s!]!^%Q!^!}!s!}#O%V#O#P%[#P#Q-t#Q#o!s#o#p-y#p#q!s#q#r.O#r;'S!s;'S;=`#n<%lO!s~!x[^~OX!sZ]!s^p!sqt!svx!sz!]!s!^!}!s#Q#o!s#p#q!s#r;'S!s;'S;=`#n<%lO!s~#qP;=`<%l!s~#ySf~XY#tYZ#t]^#tpq#t~$[Op~~$aT]~OY$[Z]$[^;'S$[;'S;=`$p<%lO$[~$sP;=`<%l$[~${On~~%QOo~~%VOr~~%[Ol~~%_U!c!}%q#T#U%q#U#V%|#V#X%q#X#Y*Z#Y#o%q~%vQW~!c!}%q#T#o%q~&RSW~!c!}%q#T#X%q#X#Y&_#Y#o%q~&dSW~!c!}%q#T#Z%q#Z#[&p#[#o%q~&uSW~!c!}%q#T#]%q#]#^'R#^#o%q~'WSW~!c!}%q#T#b%q#b#c'd#c#o%q~'iRW~!c!}%q#T#o%q#o#p'r~'uQ#g#h'{#h#i(p~(OP#V#W(R~(UP#c#d(X~([P#d#e(_~(bP#X#Y(e~(hP#q#r(k~(pOT~~(sP#]#^(v~(yP#_#`(|~)PP#n#o)S~)VP#d#e)Y~)]P#]#^)`~)cP#V#W)f~)iP#h#i)l~)oP#i#j)r~)uP#f#g)x~){P#X#Y*O~*RP#q#r*U~*ZOR~~*`SW~!c!}%q#T#b%q#b#c*l#c#o%q~*qSW~!c!}%q#T#W%q#W#X*}#X#o%q~+SRW~!c!}%q#T#o%q#o#p+]~+`Q#g#h+f#h#i,Z~+iP#V#W+l~+oP#c#d+r~+uP#d#e+x~+{P#X#Y,O~,RP#q#r,U~,ZOU~~,^P#]#^,a~,dP#_#`,g~,jP#n#o,m~,pP#d#e,s~,vP#]#^,y~,|P#V#W-P~-SP#h#i-V~-YP#i#j-]~-`P#f#g-c~-fP#X#Y-i~-lP#q#r-o~-tO_~~-yOm~~.OOj~~.TOk~",
  tokenizers: [0],
  topRules: {"Document":[0,1]},
  tokenPrec: 203
})
